# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2.1
orbs:
  socket_drano:
    executors:
      elixir:
        parameters:
          elixir:
            description: Elixir version to used by the job
            type: string
          otp:
            description: OTP release to used by the job
            type: string
        docker:
          - image: arkgil/alpine-elixir:<<parameters.elixir>>-otp-<<parameters.otp>>

    jobs:
      build_and_test:
        parameters:
          elixir:
            description: Elixir version to used by the job
            type: string
          otp:
            description: OTP release to used by the job
            type: string
          codecov_flag:
            description: String the coverage reports are grouped by
            type: string
        executor:
          name: elixir
          elixir: <<parameters.elixir>>
          otp: <<parameters.otp>>
        steps:
          - run: mix local.hex --force
          - run: mix local.rebar --force
          - checkout
          - restore_cache:
              keys:
                - deps-<<parameters.elixir>>-<<parameters.otp>>-{{ checksum "mix.lock" }}
                - deps-<<parameters.elixir>>-<<parameters.otp>>
          - run: mix deps.get
          - run: mix format --check-formatted || echo 'skipping due to false negatives'
          - save_cache:
              key: deps-<<parameters.elixir>>-<<parameters.otp>>-{{ checksum "mix.lock" }}
              paths:
              - deps

workflows:
  build_and_test:
    jobs:
      - socket_drano/build_and_test:
          name: "1.10-otp-23"
          elixir: "1.10.3"
          otp: "23"
          codecov_flag: "1_10_otp23"
      - socket_drano/build_and_test:
          name: "1.10-otp-22"
          elixir: "1.10.3"
          otp: "22"
          codecov_flag: "1_10_otp21"
      - socket_drano/build_and_test:
          name: "1.10-otp-21"
          elixir: "1.10.3"
          otp: "21"
          codecov_flag: "1_10_otp21"
      - socket_drano/build_and_test:
          name: "1.9-otp-21"
          elixir: "1.9.4"
          otp: "21"
          codecov_flag: "1_9_otp21"
      - socket_drano/build_and_test:
          name: "1.9-otp-20"
          elixir: "1.9.4"
          otp: "20"
          codecov_flag: "1_9_otp20"
