name: Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          version-type: strict
          otp-version: 27.3.4.10
          elixir-version: 1.18.3
          rebar3-version: 3.22.0
      - run: mix format --check-formatted

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          version-type: strict
          otp-version: 27.3.4.10
          elixir-version: 1.18.3
          rebar3-version: 3.22.0
      - run: mix deps.get
        name: Deps
      - run: mix test
